import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Bot, BrainCircuit, CheckCircle2, CircuitBoard, DatabaseZap, Gauge, Layers3, LockKeyhole, Rocket, ShieldCheck, Sparkles, Workflow, Zap } from 'lucide-react';
import './styles.css';

type Stage = 'builder' | 'blueprint';
interface BuilderState { name: string; useCase: string; agents: string[]; tools: string[]; memory: string[]; workflows: string[]; approvals: string[]; outputs: string[]; }

const options = {
  agents: ['Sales Agent', 'Operations Agent', 'Content Agent', 'Customer Support Agent', 'Executive Assistant Agent', 'Finance/Reporting Agent', 'Research Agent', 'Project Delivery Agent', 'Compliance Agent'],
  tools: ['Website / landing pages', 'Email inbox', 'Calendar', 'CRM', 'Airtable / Sheets', 'Slack / Teams', 'Notion / Docs / Drive', 'Stripe / billing', 'Analytics / BI', 'Support desk'],
  memory: ['Company profile', 'Offers and pricing', 'SOPs and policies', 'Brand voice', 'Customer context', 'Meeting notes', 'Research library', 'KPIs and targets'],
  workflows: ['Lead capture and qualification', 'Follow-up drafting', 'Meeting notes to action items', 'Content repurposing', 'Support response drafts', 'Weekly executive brief', 'Proposal builder', 'Project handoff routing', 'Revenue reporting'],
  approvals: ['Customer message approval', 'Publishing approval', 'Billing/payment approval', 'High-value lead escalation', 'Manager review for sensitive decisions', 'Audit log for all agent actions'],
  outputs: ['Control plane dashboard', 'Agent task board', 'Approval queue', 'Memory vault map', 'Workflow dependency map', 'Weekly operating brief', 'Implementation roadmap'],
};

function toggle(values: string[], item: string): string[] { return values.includes(item) ? values.filter((value) => value !== item) : [...values, item]; }
function Pill({ item, active, onClick }: { item: string; active: boolean; onClick: () => void }): React.ReactElement { return <button className={`pill ${active ? 'active' : ''}`} onClick={onClick} type="button"><CheckCircle2 size={16}/>{item}</button>; }

function App(): React.ReactElement {
  const [stage, setStage] = useState<Stage>('builder');
  const [state, setState] = useState<BuilderState>({ name: '', useCase: '', agents: ['Sales Agent', 'Executive Assistant Agent'], tools: ['Email inbox', 'Calendar', 'CRM'], memory: ['Company profile', 'Offers and pricing'], workflows: ['Lead capture and qualification', 'Weekly executive brief'], approvals: ['Customer message approval'], outputs: ['Control plane dashboard', 'Approval queue'] });
  const score = useMemo(() => Math.min(100, state.agents.length * 7 + state.tools.length * 5 + state.memory.length * 6 + state.workflows.length * 7 + state.approvals.length * 5 + state.outputs.length * 4), [state]);
  const tier = score >= 80 ? 'Enterprise Control Plane' : score >= 60 ? 'Business Operating Control Plane' : score >= 40 ? 'Team Workflow Control Plane' : 'Starter Agent Control Plane';
  const timeline = score >= 80 ? '8–12+ weeks' : score >= 60 ? '4–8 weeks' : score >= 40 ? '2–4 weeks' : '1–2 weeks';

  return <main><header className="topbar"><div className="brand"><CircuitBoard size={28}/><span><strong>Agentic Control Plane</strong><em>Builder</em></span></div><button className="ghost" onClick={() => setStage(stage === 'builder' ? 'blueprint' : 'builder')}>{stage === 'builder' ? 'View Blueprint' : 'Back to Builder'}</button></header>{stage === 'builder' ? <Builder state={state} setState={setState} score={score} tier={tier} timeline={timeline} onBlueprint={() => setStage('blueprint')} /> : <Blueprint state={state} score={score} tier={tier} timeline={timeline} onBack={() => setStage('builder')} />}</main>;
}

function Builder({ state, setState, score, tier, timeline, onBlueprint }: { state: BuilderState; setState: React.Dispatch<React.SetStateAction<BuilderState>>; score: number; tier: string; timeline: string; onBlueprint: () => void }): React.ReactElement {
  return <section className="shell"><div className="hero"><div><p className="eyebrow"><Sparkles size={16}/> Standalone application</p><h1>Build an agentic control plane before you build agents.</h1><p className="lede">Design the operating layer for agent teams: tools, memory, workflows, approval gates, dashboards, and launch plan.</p><div className="actions"><button className="primary" onClick={onBlueprint}>Generate Blueprint <ArrowRight size={18}/></button><a className="secondary" href="#builder">Configure Modules</a></div></div><Summary score={score} tier={tier} timeline={timeline} state={state}/></div><section id="builder" className="builder-grid"><div className="config-panel"><label>Project / organization name<input value={state.name} onChange={(event) => setState({ ...state, name: event.target.value })} placeholder="Example: Acme Ops Control Plane" /></label><label>Primary use case<textarea value={state.useCase} onChange={(event) => setState({ ...state, useCase: event.target.value })} placeholder="Describe the business, team, or operational workflow this control plane should run." /></label><OptionGroup title="1. Agent team" field="agents" state={state} setState={setState} items={options.agents}/><OptionGroup title="2. Tool/app connectors" field="tools" state={state} setState={setState} items={options.tools}/><OptionGroup title="3. Memory vault" field="memory" state={state} setState={setState} items={options.memory}/><OptionGroup title="4. Workflows to orchestrate" field="workflows" state={state} setState={setState} items={options.workflows}/><OptionGroup title="5. Approval and governance rules" field="approvals" state={state} setState={setState} items={options.approvals}/><OptionGroup title="6. Outputs and dashboards" field="outputs" state={state} setState={setState} items={options.outputs}/></div><aside className="sticky"><Summary score={score} tier={tier} timeline={timeline} state={state}/><button className="primary full" onClick={onBlueprint}>Generate Full Blueprint</button></aside></section></section>;
}

function OptionGroup({ title, field, state, setState, items }: { title: string; field: keyof Pick<BuilderState, 'agents' | 'tools' | 'memory' | 'workflows' | 'approvals' | 'outputs'>; state: BuilderState; setState: React.Dispatch<React.SetStateAction<BuilderState>>; items: string[] }): React.ReactElement { return <section className="option-group"><div className="group-head"><h2>{title}</h2><span>{state[field].length} selected</span></div><div className="pill-grid">{items.map((item) => <Pill key={item} item={item} active={state[field].includes(item)} onClick={() => setState({ ...state, [field]: toggle(state[field], item) })} />)}</div></section>; }

function Summary({ score, tier, timeline, state }: { score: number; tier: string; timeline: string; state: BuilderState }): React.ReactElement { return <article className="summary-card"><div className="score"><strong>{score}</strong><span>/100</span></div><h2>{tier}</h2><p>{state.name || 'Your control plane'} is estimated as a <b>{timeline}</b> implementation.</p><div className="summary-stats"><span><Bot size={15}/>{state.agents.length} agents</span><span><Layers3 size={15}/>{state.tools.length} tools</span><span><Workflow size={15}/>{state.workflows.length} workflows</span><span><ShieldCheck size={15}/>{state.approvals.length} approvals</span></div></article>; }

function Blueprint({ state, score, tier, timeline, onBack }: { state: BuilderState; score: number; tier: string; timeline: string; onBack: () => void }): React.ReactElement { const sections = [{ title: 'Agent Team', icon: Bot, items: state.agents }, { title: 'Connected Tools', icon: Layers3, items: state.tools }, { title: 'Memory Vault', icon: DatabaseZap, items: state.memory }, { title: 'Workflow Orchestration', icon: Workflow, items: state.workflows }, { title: 'Approval Controls', icon: LockKeyhole, items: state.approvals }, { title: 'Dashboards and Outputs', icon: Gauge, items: state.outputs }]; return <section className="shell blueprint"><div className="page-head"><p className="eyebrow"><Rocket size={16}/> Generated blueprint</p><h1>{state.name || 'Agentic Control Plane Blueprint'}</h1><p>{state.useCase || 'A configurable operating layer for agent teams, memory, tools, workflows, approvals, and outputs.'}</p></div><div className="blueprint-top"><Summary score={score} tier={tier} timeline={timeline} state={state}/><article className="launch-plan"><h2>Recommended implementation path</h2><ol><li>Confirm target business workflows and owners.</li><li>Connect tools and define permission boundaries.</li><li>Build memory vault from docs, SOPs, offers, and decisions.</li><li>Configure first agent team and approval queue.</li><li>Launch dashboards, weekly briefs, and workflow reporting.</li></ol></article></div><div className="blueprint-grid">{sections.map((section) => { const Icon = section.icon; return <article className="blueprint-card" key={section.title}><Icon size={24}/><h2>{section.title}</h2><ul>{section.items.map((item) => <li key={item}><CheckCircle2 size={15}/>{item}</li>)}</ul></article>; })}</div><div className="actions centered"><button className="secondary" onClick={onBack}>Edit Builder</button><button className="primary" onClick={() => window.print()}>Print / Save Blueprint</button></div></section>; }

createRoot(document.getElementById('root')!).render(<App />);
